global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
  - job_name: 'agent1'
    static_configs:
      - targets: ['agent1:5000']
  - job_name: 'agent2'
    static_configs:
      - targets: ['agent2:5000']
